# Generated by Django 4.2.5 on 2023-09-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='genre',
            new_name='diet',
        ),
    ]
