# Generated by Django 4.2.5 on 2023-09-25 12:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Рецепт-ингредиент', 'verbose_name_plural': 'Рецепт-ингредиенты'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement',
            field=models.IntegerField(choices=[(1, 'Шт'), (2, 'Гр.'), (3, 'Мл')], default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dairy',
            field=models.BooleanField(default=False, verbose_name='Молочные продукты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fish',
            field=models.BooleanField(default=False, verbose_name='Рыба'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='honey',
            field=models.BooleanField(default=False, verbose_name='Продукты пчеловодства'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal',
            field=models.IntegerField(choices=[(1, 'Завтраки'), (2, 'Обеды'), (3, 'Ужины'), (4, 'Десерты')], verbose_name='Приём пищи'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meat',
            field=models.BooleanField(default=False, verbose_name='Мясо'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nuts',
            field=models.BooleanField(default=False, verbose_name='Орехи'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='wheat',
            field=models.BooleanField(default=False, verbose_name='Зерновые'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='dairy',
            field=models.BooleanField(default=False, verbose_name='Молочные продукты'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='diet',
            field=models.IntegerField(choices=[(1, 'Classic'), (2, 'Low carb'), (3, 'Vegan'), (4, 'Keto')], verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='fish',
            field=models.BooleanField(default=False, verbose_name='Рыба'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='honey',
            field=models.BooleanField(default=False, verbose_name='Продукты пчеловодства'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='meal',
            field=models.IntegerField(choices=[(1, 'Завтраки'), (2, 'Обеды'), (3, 'Ужины'), (4, 'Десерты')], verbose_name='Приём пищи'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='meat',
            field=models.BooleanField(default=False, verbose_name='Мясо'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='nuts',
            field=models.BooleanField(default=False, verbose_name='Орехи'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='people_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Value must be at least 1.'), django.core.validators.MaxValueValidator(6, message='Value cannot be greater than 6.')], verbose_name='На сколько персон'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='term',
            field=models.IntegerField(choices=[(1, '1 мес.'), (2, '3 мес.'), (3, '6 мес.'), (4, '12 мес.')], verbose_name='Срок подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='wheat',
            field=models.BooleanField(default=False, verbose_name='Зерновые'),
        ),
    ]
