# Generated by Django 4.2.5 on 2023-09-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.IntegerField(choices=[(1, 'Шт'), (2, 'Гр.'), (3, 'Мл')], default=2),
        ),
    ]
