# Generated by Django 4.2.5 on 2023-09-22 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('recipe', '0003_recipe_dairy_recipe_fish_recipe_honey_recipe_meat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.IntegerField(choices=[(1, 'Classic'), (2, 'Low carb'), (3, 'Vegan'), (4, 'Keto')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
        ),
    ]
