# Generated by Django 4.2.5 on 2023-09-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementunit',
            name='weight',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
