# Generated by Django 4.2.5 on 2023-09-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_ingredient_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='meal',
        ),
    ]
