# Generated by Django 4.2.5 on 2023-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_remove_subscription_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='breakfast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dessert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dinner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lunch',
            field=models.BooleanField(default=True),
        ),
    ]
