# Generated by Django 4.2.5 on 2023-09-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_measurementunit_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
    ]
