# Generated by Django 4.2.5 on 2023-09-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_subscription_breakfast_subscription_dessert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=' вариант соте из баклажанов (аджапсандали) на лепешках из кукурузной муки с сыром (чвиштари). Этот рецепт просто очаровал меня своим сказочным названием. Потом оказалось, что и вкус блюда полностью оправдывает самые сказочные ожидания. А готовить его оказалось вполне просто.', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='breakfast',
            field=models.BooleanField(default=True, verbose_name='Завтрак'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='dessert',
            field=models.BooleanField(default=True, verbose_name='Десерт'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='dinner',
            field=models.BooleanField(default=True, verbose_name='Ужин'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='lunch',
            field=models.BooleanField(default=True, verbose_name='Обед'),
        ),
    ]
