version: '3.8'

services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./static:/static
      - ./media:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1337:80
      - 80:80
    depends_on:
      - api
  api:
    image: pavel2232/foodplan:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    restart: always
    env_file:
      - .env
    volumes:
      - ./static:/static
      - ./media:/media
    expose:
      - 8000
    container_name: foodplan


